platform :ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mimikgit/cocoapod-edge-specs.git'

target 'Random-Number-Generator-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Random-Number-Generator-Example
  pod 'MIMIKEdgeClient'
  pod 'MIMIKEdgeClientIdentity'
  pod 'Alamofire'
end